# Variabili Colore
$primary = rgb(1e3a5f)          # Il tuo nuovo Blu Spazio per la selezione
$surface = rgb(191724)          # Sfondo scuro originale
$secondary = rgb(1e3a5f)        # Usato per i gruppi e gli slider
$error = rgb(eb6f92)
$tertiary = rgb(31748f)
$surface_lowest = rgb(1b1928)
$accent_pink = rgb(ebbcba)      # Il tuo rosa antico salvato qui

general {
    # Applica il blu al bordo della finestra attiva
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    # Applica il blu ai gruppi di finestre
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        # Colore della barra superiore dei gruppi (lo "slider" dei tab)
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}