# SYSTEMWIDE CURSOR
env = HYPRCURSOR_THEME,Bibata-Modern-Classic
env = HYPRCURSOR_SIZE,24
env = XCURSOR_THEME,Bibata-Modern-Classic
env = XCURSOR_SIZE,24
env = QT_CURSOR_THEME,Bibata-Modern-Classic
env = QT_CURSOR_SIZE,24

general {
    gaps_in = 2 
    gaps_out = 2
    border_size = 2

    # Il tuo Blu Spazio come colore unico per il bordo attivo
    col.active_border = rgba(1e3a5fff) 45deg
    
    # Blu molto scuro quasi nero per le finestre inattive
    col.inactive_border = rgba(070722cc) 45deg

    resize_on_border = true
    allow_tearing = false
    layout = dwindle
}

group {
    # Coerenza cromatica per i gruppi di finestre
    col.border_active = rgba(1e3a5fff) 45deg
    col.border_inactive = rgba(070722cc) 45deg
    
    groupbar {
        col.active = rgba(1e3a5fff)
        col.inactive = rgba(070722cc)
        text_color = rgba(ffffffff) # Testo bianco
    }
}

decoration {
    rounding = 15
    active_opacity = 1.0
    inactive_opacity = 0.90

    # Ombra blu per richiamare il tema di selezione
    shadow {
        enabled = true
        range = 10
        render_power = 3
        color = rgba(1e3a5f66)
    }

    blur {
        enabled = yes
        size = 1
        passes = 3
        new_optimizations = on
        ignore_opacity = on
        xray = false
        special = true
    }
}